# https://hub.docker.com/_/microsoft-dotnet

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

#Build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /build_settings AS setting
ARG shared_path

WORKDIR /src
COPY sample-docker-dotin.csproj sample-docker/
RUN dotnet restore "sample-docker/sample-docker-dotin.csproj"

WORKDIR /src/sample-docker
COPY . .
RUN dotnet build "sample-docker-dotin.csproj" -c Release -o /app/build

#Publish stage
FROM build AS publish
RUN dotnet publish "sample-docker-dotin.csproj" -c Release -o /app/publish

COPY $shared_path /app/publish

#Finalizing image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "sample-docker-dotin.dll"]